version: '3.8'
networks:
  primary_simrs:
services:
  nginx_primary:
    image: nginx:alpine
    container_name: nginx_primary
    ports:
      - '8036:8036'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - primary_simrs
      - primary_simrs_db
    networks:
      - primary_simrs
  primary_simrs_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'primary_simrs'
      MYSQL_USER: 'dimas'
      MYSQL_PASSWORD: 'dimas1950'
      MYSQL_ROOT_PASSWORD: 'dimas1950'
    ports:
      - '3307:3306'
    networks:
      - primary_simrs

  primary_simrs:
    container_name: primary_simrs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - primary_simrs
